### PR TITLE
Adding auto scrapping for DU cutoffs

### PR DESCRIPTION
**Pull request by pokymono**
We will utilize "Shiksha.com" to scrape cutoff data efficiently, bypassing the need to log in to the CUET portal, which requires sensitive information such as the application number, phone number, date of birth, and security pin. This approach simplifies our task by eliminating the need to input sensitive data, making the process more straightforward.

### CODE REVIEW

**Comment by Sohammhatre10** [comment]
1. Instead of creating two different files maybe call the Web-driver twice using two functions in the main(). 
2. The format for the csv generated must be `College-name`, `Program`,`Category`, `Gender`, `Cutoff` in that order as I am planning to store all the csv's via a MongoDB cluster. 

Overall thanks for the contribution will you please make the necessary changes and then ping me when you're donw with them.

**Comment by pokymono** [comment]
Yeah sure! I'll do the changes and send a PR by tonight.

**Comment by Sohammhatre10** [comment]
Thanks!
This is the example format for your reference
`College`, `Branch`, `Quota`, `Category`, `Gender`, `OpenRank`, `CloseRank`

Example for the IITmain.csv file 
`Indian Institute  of Technology Bhubaneswar`, `"Civil Engineering (4 Years, Bachelor of Technology)"`, `AI` ,`OPEN`, `Gender-Neutral`, `9106`, `14782`

**Comment by pokymono** [comment]
Hey! I've made the necessary changes according to the format you suggested. I hope this works!

**Comment by Sohammhatre10** [comment]
Thanks for the contribution! This PR caters to https://github.com/Sohammhatre10/Cadmi_AI/issues/3

**Pull request merged**
